<?php

defined( 'ABSPATH' ) || exit;  
?>

<div class="molongui-guest-profile-picture" data-molongui-avatar-container data-molongui-avatar-fallback-label="<?php esc_attr_e( 'Default avatar', 'molongui-authorship' ); ?>">

	<?php if ( ! empty( $profile_picture['avatar'] ) ) : ?>

		<div class="molongui-guest-profile-picture__preview">
			<?php echo $profile_picture['avatar']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by the internal Avatar renderer. ?>

			<?php if ( ! empty( $profile_picture['source'] ) ) : ?>
				<span class="molongui-profile-picture-source" data-molongui-avatar-source>
					<?php echo esc_html( $profile_picture['source'] ); ?>
				</span>
			<?php endif; ?>
		</div>

	<?php else : ?>

		<p class="description">
			<?php esc_html_e( 'No profile picture is currently available for this author.', 'molongui-authorship' ); ?>
		</p>

	<?php endif; ?>

	<p class="description">
		<?php
		esc_html_e(
			'The picture shown here follows the global Author Avatar Settings.',
			'molongui-authorship'
		);
		?>
	</p>

	<p>
		<a class="button" href="<?php echo esc_url( $profile_picture['settings_url'] ); ?>">
			<?php esc_html_e( 'Open Avatar Settings', 'molongui-authorship' ); ?>
		</a>
	</p>

</div>
